### PR TITLE
Start elm cheatsheet

### LINKED ISSUE #157: Cheatsheet request: Elm
```
# compile elm file to js
elm-make <.elm file> --output=<.js file>

# open dev live web server on your default browser
elm-live <.elm file> --open --output=<.js file>
```

### LINKED ISSUE #310: Cheatsheet request: elm

### LINKED ISSUE #360: Cheatsheet request: ELM

### LINKED ISSUE #490: Cheatsheet request:ELM
possible to add a cheat sheet for ELM ?

### PR DESCRIPTION
**Pull request by tuxagon**
Fixes #157 Fixes #310 Fixes #360 Fixes #490 

I started the elm cheatsheet. There is probably more that could go into it, but I thought this was a good starting point for now.

### CODE REVIEW

**Comment by rstacruz** [comment]
Wow, that's pretty detailed, awesome work! Thank you so much. <3

**Comment by tuxagon** [comment]
I had some spare time and I know elm 😄

**Comment by absynce** [comment]
Yes! Great work @tuxagon...and thanks for the platform and other sheets @rstacruz. These cheat sheets are really helpful!

This was the first sheet I tried to look up. 😝 I always forget record pattern matching/destructuring in a function definition...and you have it here!

A couple suggestions:
* Update for 0.19
  * No `toString` function
  * Union types are now called "Custom Types"
  * Add `--optimize` flag for `elm make`
* Examples wiring up `Browser.sandbox`, `Browser.element`, `Browser.document`, and `Browser.application` from the JavaScript side:
```javascript
var app = Elm.Main.init({
  node: document.getElementById('elm')
});
app.ports.cache.subscribe(function(data) {
  localStorage.setItem('cache', JSON.stringify(data));
});
```

I will have some time in a couple weeks to make these changes if you all are busy and fine with that.

**Comment by tuxagon** [comment]
@absynce If you're comfortable, go ahead and make the updates. I have been pretty busy lately and haven't gotten around to really playing with 0.19 yet and not sure when I'll actually be able to.

**Pull request closed without merging**
