### PR TITLE
sed: fix "!p" example

### PR DESCRIPTION
**Pull request by tripleee**

### CODE REVIEW

**Comment by tripleee** [comment]
I'm wondering if there should be a section with basics about the regex dialect supported out of the box and the meaning of `-E` / `-r´ if supported.

**Review by rstacruz — APPROVED** [review]

**Comment by rstacruz** [comment]
Thanks for this! I think `sed` is a bit of a tricky subject because there are two versions (GNU sed with Linux, BSD sed with MacOS). I can confirm `!p` works on the GNU version.

It might be worth noting these two different implementations of sed.

**Comment by tripleee** [comment]
Thanks. Any chance you could add the hacktoberfest tag to this one too? I'm one short ...

**Comment by tripleee** [comment]
There are more than two versions, `sed` is really tricky from a portability standpoint because there are so many variations. POSIX standardizes a small subset with some implementation details unspecified, so the behavior around e.g. labels and braces is slightly different between BSD and GNU `sed`, for example. I imagine you are not even trying to describe anything more complex than the very base behavior precisely for this reason ...?

**Pull request merged**
