### PR TITLE
Add some notes for AppleScript

### PR DESCRIPTION
**Pull request by hezhizhen**
I have just read a book about AppleScript and learned some, and I really want to share the notes here. 

I have never used Pull Request in GitHub, so I add a few notes and give a try to it.

### CODE REVIEW

**Comment by rstacruz** [comment]
Thanks! Sorry this took a while. I've also updated the layout to make it prettier.

**Comment by rstacruz** [comment]
:+1: Thanks for your contribution! :heart:

**Comment by hezhizhen** [comment]
@rstacruz It seems that there is no syntax highlighting for applescript

**Comment by rstacruz** [comment]
there isn't by default, but it's supported by prismjs (https://github.com/PrismJS/prism/tree/gh-pages/components), let me enable it just for that page

**Pull request merged**
