### PR TITLE
Add Stringification to C Preprocessor

### PR DESCRIPTION
**Pull request by g3rrit**
I added Stringification to the C Preprocessor.

I also fixed an issue with Token Concat.

### CODE REVIEW

**Comment by rstacruz** [comment]
Thanks for this! I'm not too sure this would work with most projects, it doesn't seem like STR() here would add quotes to something. Happy to be challenged here, but for now I'll close this PR.

**Comment by g3rrit** [comment]
Hi @rstacruz,

if you don't want to merge this im fine, but im sure it does add quotes.

file:
```c
#define STR(x) #x
STR(y)
``` 

produces 
```
"y"
```

if passed to `cpp -P file > outfile` as specified in the cheatsheet

Here is a reference to the doc of of the gcc compiler on this: https://gcc.gnu.org/onlinedocs/gcc-4.8.5/cpp/Stringification.html

Best regards
Gerrit

**Comment by rstacruz** [comment]
Oh nice, today I learned!

**Comment by g3rrit** [comment]
Cool thanks for merging!

**Pull request merged**
