### PR TITLE
New cheatsheet: Rollup.js

### PR DESCRIPTION
**Pull request by ryanSN**
### Goal of pr
Add [Rollup](https://rollupjs.org/) as a cheatsheet (first pass)

rollup_js_cheatsheet

### CODE REVIEW

**Comment by ryanSN** [comment]
@rstacruz need me to do anything else on this? let me know if you want me to change anything up 👍

**Comment by rstacruz** [comment]
rollup: clean up styles

**Comment by rstacruz** [comment]
Sorry this took a while, but I'm merging this now!

**Comment by rstacruz** [comment]
:+1: Thanks for your contribution! :heart:

**Pull request merged**
