### PR TITLE
GraphWPF, WPFObjects, Graph3D unit pages

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
Related issue: #1745 

# ToDos:

- [x] GraphWPF
- [x] WPFObjects
- [x] Graph3D

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
@samuraiGH, please check this pages. :)

**Comment by EmilySeville7cfg** [comment]
@rstacruz, it it going to be merged?

**Comment by rstacruz** [comment]
> @rstacruz, it it going to be merged?

Thanks for this. Do you have some URL's that show what this is for? A quick Google search for GraphWPF doesn't seem to yield much.

**Comment by EmilySeville7cfg** [comment]
Yes, they are not very popular, they are specific to PascalABC.NET. [Here](http://pascalabc.net/downloads/pabcnethelp/index.htm) are you can find GraphWPF, WPFObjects, Graph3D docs.

**Pull request closed without merging**
